version: '3'

services:
  shop_service:
    build: ./shop
    container_name: shop-fastapi-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8001
    volumes:
      - ./shop/:/shop/
    ports:
      - "8001:8001"

  shop_spider:
    build: ./scraper
    container_name: shop-spider
    volumes:
      - ./scraper/:/scraper/
    command: python app/run_spider.py shop
    depends_on:
      - mongodb
      - redis
      - shop_service

  nginx:
    image: nginx:latest
    container_name: wnginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/conf/conf.d/:/etc/nginx/conf.d
      - ./nginx/conf/ssl/:/etc/nginx/ssl
    depends_on:
      - shop_service

  database:
    build:
      context: ./database
    volumes:
      - ./database:/var/www/database
    ports:
      - "33061:33061"
    environment:
      - MYSQL_DATABASE=wechat_shop
      - MYSQL_USER=shop_admin
      - MYSQL_PASSWORD=c2hvcDEyMzQ1Ng==
      - MYSQL_ROOT_PASSWORD=c2hvcDEyMzQ1

  mongodb:
    image: mongo
    volumes:
      - ./mongodb:/data/db
    ports:
      - 7001:27017

  mongo-express:
    image: mongo-express
    ports:
      - 7002:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb

  redis:
    image: redis
    command: redis-server
    ports:
      - 7003:6379
    volumes:
      - ./redis:/data